title: Hertingfordbury Parish
url: "https://www.hertingfordbury.org.uk"

permalink: /parish-council/minutes/:name/

markdown: kramdown

subsume: https://api.subsume.io/

recaptchaKey: 6LdXUmMUAAAAADz6MfbjeGthewqTGTGsUAtMDjpQ

exclude:
  - src
